#!/bin/bash
if [ -z "$1" ]; then
	echo "Usage: $0 <usb device path>"
	echo "  (e.g. 1-1.1.3)"
	echo
	echo "Executes airclickd with the specified USB device as input"
	exit 1
fi
DEV="`find /sys/bus/usb/devices/"$1":1.0/*/hidraw/ \
	-mindepth 1 -maxdepth 1 \
	-type d -name 'hidraw*' \
	-printf %P | head -n 1`"
if [ -z "$DEV" ]; then
	echo "Cannot find a hidraw device for $1"
	exit 1
fi
exec airclickd </dev/"$DEV"
